/**
 * 共享常量配置
 *
 * 在多个工具间复用的超时与延迟设置，避免魔法数字散落在代码中。
 */

export const TIMING = {
  INITIAL_PAGE_WAIT_MS: 3000,
  LOGIN_CHECK_INTERVAL_MS: 3000,
  PROFILE_NAVIGATION_TIMEOUT_MS: 10000,
  POST_PROFILE_NAV_DELAY_MS: 3000,
  USER_ID_EXTRACTION_DELAY_MS: 2000,
  SEARCH_RESULT_RENDER_MS: 5000,
  SEARCH_SORT_DELAY_MS: 3000,
  SEARCH_SCROLL_DELAY_MS: 2000,
  HOVER_DELAY_MIN_MS: 800,
  HOVER_DELAY_MAX_MS: 1500,
  HOVER_BATCH_SIZE: 3,
  HOVER_BATCH_PAUSE_MIN_MS: 1000,
  HOVER_BATCH_PAUSE_MAX_MS: 2000
} as const;

export const USER_CONSTANTS = {
  MIN_USER_ID_LENGTH: 20
} as const;

export type TimingKeys = keyof typeof TIMING;
